apiVersion: apps/v1
kind: Deployment
metadata:
  name: starter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: starter
  template:
    metadata:
      labels:
        app: starter
    spec:
      terminationGracePeriodSeconds: 0
      containers:
        - name: starter
          image: tpmacc/starter
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: starter.variable
              value: k8s.yml

---

apiVersion: v1
kind: Service
metadata:
  name: starter
  annotations:
    dev.okteto.com/auto-ingress: "true"
  labels:
    app: starter
spec:
  type: ClusterIP
  ports:
    - name: starter
      port: 8080
  selector:
    app: starter