apiVersion: v1
kind: Service
metadata:
  name: starter-service
  labels:
    app: starter-service
spec:
  type: LoadBalancer
  ports:
    - port: 9002
  selector:
    app: starter-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: starter-service
  labels:
    app: starter-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: starter-service
  template:
    metadata:
      labels:
        app: starter-service
    spec:
      containers:
        - name: starter-service
          image: tpmacc/starter
          ports:
            - containerPort: 9002
